UPDATE GEN_SYSTEM SET DATA_PATH='d:\genesis\test';
UPDATE GEN_SYSTEM SET ORACLE_LOGON='test/test';
UPDATE GEN_SYSTEM SET ALLOW_GENESIS_TOTP='N';
UPDATE GEN_SYSTEM SET BROADCAST_MESSAGE='This is a TEST server - Data loaded as of 06/13/15';
commit;
quit;